/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTheWombWasATombRouteImport } from './routes/work.the-womb-was-a-tomb'
import { Route as WorkReimaginingFortYorkRouteImport } from './routes/work.reimagining-fort-york'
import { Route as WorkNightOfLivingMonstersRouteImport } from './routes/work.night-of-living-monsters'
import { Route as WorkMakingQueerkinsRouteImport } from './routes/work.making-queerkins'
import { Route as WorkFruitMarketRouteImport } from './routes/work.fruit-market'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTheWombWasATombRoute = WorkTheWombWasATombRouteImport.update({
  id: '/the-womb-was-a-tomb',
  path: '/the-womb-was-a-tomb',
  getParentRoute: () => WorkRoute,
} as any)
const WorkReimaginingFortYorkRoute = WorkReimaginingFortYorkRouteImport.update({
  id: '/reimagining-fort-york',
  path: '/reimagining-fort-york',
  getParentRoute: () => WorkRoute,
} as any)
const WorkNightOfLivingMonstersRoute =
  WorkNightOfLivingMonstersRouteImport.update({
    id: '/night-of-living-monsters',
    path: '/night-of-living-monsters',
    getParentRoute: () => WorkRoute,
  } as any)
const WorkMakingQueerkinsRoute = WorkMakingQueerkinsRouteImport.update({
  id: '/making-queerkins',
  path: '/making-queerkins',
  getParentRoute: () => WorkRoute,
} as any)
const WorkFruitMarketRoute = WorkFruitMarketRouteImport.update({
  id: '/fruit-market',
  path: '/fruit-market',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/work/fruit-market': typeof WorkFruitMarketRoute
  '/work/making-queerkins': typeof WorkMakingQueerkinsRoute
  '/work/night-of-living-monsters': typeof WorkNightOfLivingMonstersRoute
  '/work/reimagining-fort-york': typeof WorkReimaginingFortYorkRoute
  '/work/the-womb-was-a-tomb': typeof WorkTheWombWasATombRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/work/fruit-market': typeof WorkFruitMarketRoute
  '/work/making-queerkins': typeof WorkMakingQueerkinsRoute
  '/work/night-of-living-monsters': typeof WorkNightOfLivingMonstersRoute
  '/work/reimagining-fort-york': typeof WorkReimaginingFortYorkRoute
  '/work/the-womb-was-a-tomb': typeof WorkTheWombWasATombRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/work/fruit-market': typeof WorkFruitMarketRoute
  '/work/making-queerkins': typeof WorkMakingQueerkinsRoute
  '/work/night-of-living-monsters': typeof WorkNightOfLivingMonstersRoute
  '/work/reimagining-fort-york': typeof WorkReimaginingFortYorkRoute
  '/work/the-womb-was-a-tomb': typeof WorkTheWombWasATombRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/work'
    | '/work/fruit-market'
    | '/work/making-queerkins'
    | '/work/night-of-living-monsters'
    | '/work/reimagining-fort-york'
    | '/work/the-womb-was-a-tomb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/work'
    | '/work/fruit-market'
    | '/work/making-queerkins'
    | '/work/night-of-living-monsters'
    | '/work/reimagining-fort-york'
    | '/work/the-womb-was-a-tomb'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/work'
    | '/work/fruit-market'
    | '/work/making-queerkins'
    | '/work/night-of-living-monsters'
    | '/work/reimagining-fort-york'
    | '/work/the-womb-was-a-tomb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/the-womb-was-a-tomb': {
      id: '/work/the-womb-was-a-tomb'
      path: '/the-womb-was-a-tomb'
      fullPath: '/work/the-womb-was-a-tomb'
      preLoaderRoute: typeof WorkTheWombWasATombRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/reimagining-fort-york': {
      id: '/work/reimagining-fort-york'
      path: '/reimagining-fort-york'
      fullPath: '/work/reimagining-fort-york'
      preLoaderRoute: typeof WorkReimaginingFortYorkRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/night-of-living-monsters': {
      id: '/work/night-of-living-monsters'
      path: '/night-of-living-monsters'
      fullPath: '/work/night-of-living-monsters'
      preLoaderRoute: typeof WorkNightOfLivingMonstersRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/making-queerkins': {
      id: '/work/making-queerkins'
      path: '/making-queerkins'
      fullPath: '/work/making-queerkins'
      preLoaderRoute: typeof WorkMakingQueerkinsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/fruit-market': {
      id: '/work/fruit-market'
      path: '/fruit-market'
      fullPath: '/work/fruit-market'
      preLoaderRoute: typeof WorkFruitMarketRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkFruitMarketRoute: typeof WorkFruitMarketRoute
  WorkMakingQueerkinsRoute: typeof WorkMakingQueerkinsRoute
  WorkNightOfLivingMonstersRoute: typeof WorkNightOfLivingMonstersRoute
  WorkReimaginingFortYorkRoute: typeof WorkReimaginingFortYorkRoute
  WorkTheWombWasATombRoute: typeof WorkTheWombWasATombRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkFruitMarketRoute: WorkFruitMarketRoute,
  WorkMakingQueerkinsRoute: WorkMakingQueerkinsRoute,
  WorkNightOfLivingMonstersRoute: WorkNightOfLivingMonstersRoute,
  WorkReimaginingFortYorkRoute: WorkReimaginingFortYorkRoute,
  WorkTheWombWasATombRoute: WorkTheWombWasATombRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
